title: Namuk Ko
profile_img: /assets/img/man-wearing-glasses-icon.webp
icon_img: /assets/img/icon.webp

name: "Namuk Ko"
job: "Data Engineer | 대규모 벡터 검색 인프라 구축 · 데이터 거버넌스"

phone_number: 010-5840-4634
address: Seoul, Korea
email: kmu1009@gmail.com
linkedin_username: namuk-ko-4880b11b8
#github_username: github
#instagram_username: instagram
#twitter_username: twitter
#facebook_username: facebook
#youtube_username: youtube
#blog_url: homepage-url

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
